language: generic
env:
  - EMACS_VERSION=25.3-travis
  - EMACS_VERSION=26.2-travis

install:
  - curl -fsSkL https://raw.githubusercontent.com/rejeep/evm/master/go | bash
  - export PATH="$HOME/.evm/bin:$PATH"
  - evm config path /tmp
  - evm install emacs-$EMACS_VERSION
  - export PATH="/tmp/emacs-$EMACS_VERSION/bin:$PATH"

script:
  - make make
